# KallistiOS ##version##
#
# thread/Makefile
# Copyright (C) 2001 Megan Potter
#

OBJS =  sem.o cond.o mutex.o genwait.o
OBJS += thread.o rwsem.o once.o tls.o barrier.o
OBJS += oneshot_timer.o worker.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



