# KallistiOS ##version##
#
# examples/dreamcast/pthread/Makefile
# Copyright (C) 2023 Lawrence Sebald
#

all:
	$(KOS_MAKE) -C general

clean:
	$(KOS_MAKE) -C general clean

dist:
	$(KOS_MAKE) -C general dist
